<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class Books extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::unprepared("INSERT INTO `books` (`id`, `author_id`, `title`, `slug`, `excerpt`, `body`, `created_at`, `updated_at`) VALUES
        (1, 6, 'Pride and Prejudice', 'pride-and-prejudice', 'A tour de force of wit and sparkling dialogue, with characters and themes that still resonate today. Both a romance full of gowns and', 'A tour de force of wit and sparkling dialogue, with characters and themes that still resonate today. Both a romance full of gowns andA tour de force of wit and sparkling dialogue, with characters and themes that still resonate today. Both a romance full of gowns andA tour de force of wit and sparkling dialogue, with characters and themes that still resonate today. Both a romance full of gowns andA tour de force of wit and sparkling dialogue, with characters and themes that still resonate today. Both a romance full of gowns and', '2023-12-04 21:05:46', '2023-12-07 16:53:42'),
        (2, 7, 'Great Expectations', 'great-expectations', 'One of the most renowned novels by this Victorian great, if you\'re looking for a Charles Dickens book to tick off of your literary bucket list, Great Expectations is a must-read.', 'One of the most renowned novels by this Victorian great, if you\'re looking for a Charles Dickens book to tick off of your literary bucket list, Great Expectations is a must-read.One of the most renowned novels by this Victorian great, if you\'re looking for a Charles Dickens book to tick off of your literary bucket list, Great Expectations is a must-read.One of the most renowned novels by this Victorian great, if you\'re looking for a Charles Dickens book to tick off of your literary bucket list, Great Expectations is a must-read.One of the most renowned novels by this Victorian great, if you\'re looking for a Charles Dickens book to tick off of your literary bucket list, Great Expectations is a must-read.', '2023-12-04 21:06:19', '2023-12-04 21:06:19'),
        (3, 20, 'Little Women', 'little-women', 'Thousands of teenagers around the world have fallen in love with Marmee and her four daughters: Meg, Jo, Beth and Amy. This semi-autobiographical novel charts the highs and l', 'Thousands of teenagers around the world have fallen in love with Marmee and her four daughters: Meg, Jo, Beth and Amy. This semi-autobiographical novel charts the highs and lThousands of teenagers around the world have fallen in love with Marmee and her four daughters: Meg, Jo, Beth and Amy. This semi-autobiographical novel charts the highs and lThousands of teenagers around the world have fallen in love with Marmee and her four daughters: Meg, Jo, Beth and Amy. This semi-autobiographical novel charts the highs and l', '2023-12-04 21:06:46', '2023-12-07 16:53:29'),
        (5, 16, 'Frankenstein ', 'frankenstein', 'Often copied but never bettered, Mary Shelley’s Frankenstein is the influential and shocking story of technology-created life, and is widely considered the first ever scie', 'Often copied but never bettered, Mary Shelley’s Frankenstein is the influential and shocking story of technology-created life, and is widely considered the first ever scieOften copied but never bettered, Mary Shelley’s Frankenstein is the influential and shocking story of technology-created life, and is widely considered the first ever scieOften copied but never bettered, Mary Shelley’s Frankenstein is the influential and shocking story of technology-created life, and is widely considered the first ever scieOften copied but never bettered, Mary Shelley’s Frankenstein is the influential and shocking story of technology-created life, and is widely considered the first ever scie', '2023-12-04 21:26:52', '2023-12-07 16:53:10'),
        (6, 17, 'Orlando', 'orlando', 'Following its immortal namesake through three centuries of history, Orlando is a whimsical exploration of perceptions of gender and love', 'Following its immortal namesake through three centuries of history, Orlando is a whimsical exploration of perceptions of gender and loveFollowing its immortal namesake through three centuries of history, Orlando is a whimsical exploration of perceptions of gender and loveFollowing its immortal namesake through three centuries of history, Orlando is a whimsical exploration of perceptions of gender and love', '2023-12-04 21:30:56', '2023-12-07 16:53:21'),
        (7, 6, 'The Code of the Woosters', 'abdouu-book', 'This is the third full-length novel featuring P. G. Wodehouse’s best-known creations, the bumbling fool Bertie W', ' This is the third full-length novel featuring P. G. Wodehouse’s best-known creations, the bumbling fool Bertie W This is the third full-length novel featuring P. G. Wodehouse’s best-known creations, the bumbling fool Bertie W This is the third full-length novel featuring P. G. Wodehouse’s best-known creations, the bumbling fool Bertie W This is the third full-length novel featuring P. G. Wodehouse’s best-known creations, the bumbling fool Bertie W This is the third full-length novel featuring P. G. Wodehouse’s best-known creations, the bumbling fool Bertie W This is the third full-length novel featuring P. G. Wodehouse’s best-known creations, the bumbling fool Bertie W This is the third full-length novel featuring P. G. Wodehouse’s best-known creations, the bumbling fool Bertie W This is the third full-length novel featuring P. G. Wodehouse’s best-known creations, the bumbling fool Bertie W This is the third full-length novel featuring P. G. Wodehouse’s best-known creations, the bumbling fool Bertie W', '2023-12-06 11:00:31', '2023-12-08 15:32:05'),
        (8, 19, ' To Kill a Mockingbird', 'to-kill-a-mockingbird', 'A novel before its time, Harper Lee’s Pulitzer-prize winner addresses issues of race, inequality and segregation ', 'A novel before its time, Harper Lee’s Pulitzer-prize winner addresses issues of race, inequality and segregation A novel before its time, Harper Lee’s Pulitzer-prize winner addresses issues of race, inequality and segregation A novel before its time, Harper Lee’s Pulitzer-prize winner addresses issues of race, inequality and segregation A novel before its time, Harper Lee’s Pulitzer-prize winner addresses issues of race, inequality and segregation A novel before its time, Harper Lee’s Pulitzer-prize winner addresses issues of race, inequality and segregation A novel before its time, Harper Lee’s Pulitzer-prize winner addresses issues of race, inequality and segregation ', '2023-12-07 16:52:51', '2023-12-07 16:52:51'),
        (9, 7, 'One Hundred Years of Solitude', 'one-hundred-years-of-solitude', '  Gabriel García Márquez’s multi-generational spanning magnum opus was a landmark in Spanish literature', '  Gabriel García Márquez’s multi-generational spanning magnum opus was a landmark in Spanish literature.  Gabriel García Márquez’s multi-generational spanning magnum opus was a landmark in Spanish literature.  Gabriel García Márquez’s multi-generational spanning magnum opus was a landmark in Spanish literature.  Gabriel García Márquez’s multi-generational spanning magnum opus was a landmark in Spanish literature.  Gabriel García Márquez’s multi-generational spanning magnum opus was a landmark in Spanish literature.', '2023-12-07 16:55:00', '2023-12-07 16:55:00'),
        (10, 16, ' Brave New World', 'brave-new-world', ' One of the greatest and most prescient dystopian novels ever written, this should be on everyone’s must-read list.', ' One of the greatest and most prescient dystopian novels ever written, this should be on everyone’s must-read list. One of the greatest and most prescient dystopian novels ever written, this should be on everyone’s must-read list. One of the greatest and most prescient dystopian novels ever written, this should be on everyone’s must-read list. One of the greatest and most prescient dystopian novels ever written, this should be on everyone’s must-read list. One of the greatest and most prescient dystopian novels ever written, this should be on everyone’s must-read list. One of the greatest and most prescient dystopian novels ever written, this should be on everyone’s must-read list. One of the greatest and most prescient dystopian novels ever written, this should be on everyone’s must-read list.', '2023-12-07 16:55:44', '2023-12-07 16:55:44'),
        (12, 18, 'I Capture The Castle ', 'i-capture-the-castle', ' Cassandra Mortmain’s upbringing in a crumbling castle with her eccentric family may not be everyone’s experience', ' Cassandra Mortmain’s upbringing in a crumbling castle with her eccentric family may not be everyone’s experience Cassandra Mortmain’s upbringing in a crumbling castle with her eccentric family may not be everyone’s experience Cassandra Mortmain’s upbringing in a crumbling castle with her eccentric family may not be everyone’s experience Cassandra Mortmain’s upbringing in a crumbling castle with her eccentric family may not be everyone’s experience Cassandra Mortmain’s upbringing in a crumbling castle with her eccentric family may not be everyone’s experience Cassandra Mortmain’s upbringing in a crumbling castle with her eccentric family may not be everyone’s experience Cassandra Mortmain’s upbringing in a crumbling castle with her eccentric family may not be everyone’s experience Cassandra Mortmain’s upbringing in a crumbling castle with her eccentric family may not be everyone’s experience Cassandra Mortmain’s upbringing in a crumbling castle with her eccentric family may not be everyone’s experience Cassandra Mortmain’s upbringing in a crumbling castle with her eccentric family may not be everyone’s experience', '2023-12-07 16:57:22', '2023-12-07 16:57:22'),
        (13, 8, ' Jane Eyre', 'jane-eyre', ' One of literature’s steeliest heroines, in her short life Jane Eyre has overcome a traumatic childhood only to be ch', ' One of literature’s steeliest heroines, in her short life Jane Eyre has overcome a traumatic childhood only to be ch One of literature’s steeliest heroines, in her short life Jane Eyre has overcome a traumatic childhood only to be ch One of literature’s steeliest heroines, in her short life Jane Eyre has overcome a traumatic childhood only to be ch One of literature’s steeliest heroines, in her short life Jane Eyre has overcome a traumatic childhood only to be ch One of literature’s steeliest heroines, in her short life Jane Eyre has overcome a traumatic childhood only to be ch', '2023-12-07 16:58:06', '2023-12-07 16:58:06'),
        (14, 16, ' The Call of the Wild ', 'the-call-of-the-wild', 'Jack London was a gold prospector in the Canadian wilderness and used his experiences to write about a dog', 'Jack London was a gold prospector in the Canadian wilderness and used his experiences to write about a dogJack London was a gold prospector in the Canadian wilderness and used his experiences to write about a dogJack London was a gold prospector in the Canadian wilderness and used his experiences to write about a dogJack London was a gold prospector in the Canadian wilderness and used his experiences to write about a dogJack London was a gold prospector in the Canadian wilderness and used his experiences to write about a dog', '2023-12-07 16:59:14', '2023-12-07 16:59:14'),
        (15, 6, ' The Chrysalids ', 'the-chrysalids', 'An allegoric dystopia written in the wake of the Second World War,An allegoric dystopia written in the wake of the Second World War,', 'An allegoric dystopia written in the wake of the Second World War,An allegoric dystopia written in the wake of the Second World War,An allegoric dystopia written in the wake of the Second World War,An allegoric dystopia written in the wake of the Second World War,An allegoric dystopia written in the wake of the Second World War,An allegoric dystopia written in the wake of the Second World War,An allegoric dystopia written in the wake of the Second World War,An allegoric dystopia written in the wake of the Second World War,An allegoric dystopia written in the wake of the Second World War,An allegoric dystopia written in the wake of the Second World War,', '2023-12-07 17:00:01', '2023-12-07 17:00:01'),
        (16, 7, 'Moby-Dick', 'moby-dick', 'Every American writer since 1851 has been chasing the same whale: to somehow write a novel as epic and influential as Melville’', 'Every American writer since 1851 has been chasing the same whale: to somehow write a novel as epic and influential as Melville’Every American writer since 1851 has been chasing the same whale: to somehow write a novel as epic and influential as Melville’Every American writer since 1851 has been chasing the same whale: to somehow write a novel as epic and influential as Melville’Every American writer since 1851 has been chasing the same whale: to somehow write a novel as epic and influential as Melville’Every American writer since 1851 has been chasing the same whale: to somehow write a novel as epic and influential as Melville’Every American writer since 1851 has been chasing the same whale: to somehow write a novel as epic and influential as Melville’', '2023-12-07 17:01:04', '2023-12-07 17:01:04'),
        (17, 16, 'The Grapes of Wrath', 'the-grapes-of-wrath', 'Perhaps John Steinbeck’s finest novel, this is a beautifully evocative and, by the end, devastating read.', 'Perhaps John Steinbeck’s finest novel, this is a beautifully evocative and, by the end, devastating read.Perhaps John Steinbeck’s finest novel, this is a beautifully evocative and, by the end, devastating read.Perhaps John Steinbeck’s finest novel, this is a beautifully evocative and, by the end, devastating read.Perhaps John Steinbeck’s finest novel, this is a beautifully evocative and, by the end, devastating read.Perhaps John Steinbeck’s finest novel, this is a beautifully evocative and, by the end, devastating read.Perhaps John Steinbeck’s finest novel, this is a beautifully evocative and, by the end, devastating read.', '2023-12-08 15:31:28', '2023-12-08 15:31:28');");
    }
}
